#!/usr/bin/env python3
"""
Send Anatel certification report via Resend API.

Requires:
  RESEND_API_KEY env var
  REPORT_EMAIL env var (recipient)
"""

import json
import os
import sys
from pathlib import Path
from urllib.request import Request, urlopen

RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
REPORT_EMAIL = os.environ.get("REPORT_EMAIL", "")
SENDER = "Anatel Monitor <onboarding@resend.dev>"  # Update after domain verification


def send_email(subject: str, html_body: str):
    if not RESEND_API_KEY:
        print("ERROR: RESEND_API_KEY not set", file=sys.stderr)
        sys.exit(1)
    if not REPORT_EMAIL:
        print("ERROR: REPORT_EMAIL not set", file=sys.stderr)
        sys.exit(1)

    payload = json.dumps({
        "from": SENDER,
        "to": [REPORT_EMAIL],
        "subject": subject,
        "html": html_body,
    }).encode("utf-8")

    req = Request(
        "https://api.resend.com/emails",
        data=payload,
        headers={
            "Authorization": f"Bearer {RESEND_API_KEY}",
            "Content-Type": "application/json",
        },
    )

    with urlopen(req) as resp:
        result = json.loads(resp.read())
        print(f"Email sent: {result}")


def build_html(report_path: str) -> tuple[str, str]:
    """Build email subject and HTML body from report file."""
    with open(report_path, encoding="utf-8") as f:
        report = json.load(f)

    items = report.get("new_items", [])
    date = report.get("date", "")
    total = len(items)

    if total == 0:
        subject = f"[Anatel] Sem novos produtos — {date}"
        body = "<p>Nenhum novo produto certificado detectado para as marcas monitoradas.</p>"
        return subject, body

    subject = f"[Anatel] {total} novos produtos detectados — {date}"

    rows = ""
    for item in items:
        rows += f"""<tr>
            <td style="padding:6px;border:1px solid #ddd;font-weight:bold">{item['brand']}</td>
            <td style="padding:6px;border:1px solid #ddd">{item['modelo']}</td>
            <td style="padding:6px;border:1px solid #ddd">{item.get('nome_comercial','')}</td>
            <td style="padding:6px;border:1px solid #ddd">{item['data_homologacao']}</td>
            <td style="padding:6px;border:1px solid #ddd">{item['tipo_produto']}</td>
        </tr>"""

    # Summary by brand
    by_brand = {}
    for item in items:
        by_brand.setdefault(item["brand"], 0)
        by_brand[item["brand"]] += 1
    summary = " | ".join(f"{b}: {c}" for b, c in sorted(by_brand.items()))

    body = f"""
    <div style="font-family:Arial,sans-serif;max-width:800px;margin:0 auto">
        <h2 style="color:#1a365d">Anatel — Novos Produtos Certificados</h2>
        <p style="color:#666">Data: {date} | {summary}</p>
        <table style="border-collapse:collapse;width:100%;font-size:13px">
            <thead>
                <tr style="background:#f7f7f7">
                    <th style="padding:8px;border:1px solid #ddd;text-align:left">Brand</th>
                    <th style="padding:8px;border:1px solid #ddd;text-align:left">Modelo</th>
                    <th style="padding:8px;border:1px solid #ddd;text-align:left">Nome Comercial</th>
                    <th style="padding:8px;border:1px solid #ddd;text-align:left">Data</th>
                    <th style="padding:8px;border:1px solid #ddd;text-align:left">Tipo</th>
                </tr>
            </thead>
            <tbody>{rows}</tbody>
        </table>
        <hr style="margin:20px 0;border:none;border-top:1px solid #eee">
        <p style="color:#999;font-size:11px">Generated by Anatel Monitor</p>
    </div>
    """
    return subject, body


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python send_report.py <report.json>")
        sys.exit(1)

    subject, body = build_html(sys.argv[1])
    print(f"Subject: {subject}")

    if "--dry-run" in sys.argv:
        print(body)
    else:
        send_email(subject, body)
